name: Google Cloud Function Deploy

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: form-processing
          runtime: nodejs14
          entry_point: main
          region: europe-west3
          env_vars: GOOGLE_SHEET_ID=${{ secrets.GOOGLE_SHEET_ID }},SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }},MAIL_TO=${{ secrets.MAIL_TO }},MAIL_REPLYTO=${{ secrets.MAIL_REPLYTO }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}
